### ISSUE TITLE
Error on non containerized environment

### ISSUE THREAD

**Issue by Keivhin** [muno92/resharper_inspectcode#277]
Hi !

I'm using your action on a non containerized Windows environment. However the first time worked, the second time, I got an error because jetbrains.resharper.globaltools is already installed. Is there any chance we get a fix if tool is already installed ?

Thanks :)

**Comment by muno92** [comment]
Sorry, I missed the consideration of self-hosted runner.

I'll try to fix it.

Please wait for a little while.

**Comment by muno92** [comment]
Hi, @Keivhin .

I fixed action in version 1.4.1

Is it work on your environment?

**Comment by Keivhin** [comment]
Thanks ! I'll try that :)
