### ISSUE TITLE
Request to have a minimum severity level for annotations

### ISSUE THREAD

**Issue by ashek-simeon** [muno92/resharper_inspectcode#391]
Right now, it does not seem that there is a way to, for instance, only show annotations for warnings and above.

Possibly this could be achieved by adding a new parameter to the action, and passing it to the --severity option of jb inspectcode.

Thanks for your consideration!

**Comment by muno92** [comment]
@ashek-simeon  
Thank you for suggestion! 

I add option minimumReportSeverity on version 1.7.0 .
So, you can specify minimum annotation level with version 1.7.0 or higher.

Regards.

**Comment by muno92** [comment]
It's not typo...

minimumSeverity is another option to specify action failure level.
You can use this option when annotation target is different from issue level what you want to fail job. 

The following is example.

- minimumSeverity
  - warning
- minimumReportSeverity
  - info

Output
- annotation
  - info or higher
- inspection job failed
  - when warning or error is exists

I think it is too confusing, but for backward compatibility, I keep both option while 1.x.

**Comment by ashek-simeon** [comment]
I meant that it looks like minimumSeverity is listed twice

![image](https://github.com/muno92/resharper_inspectcode/assets/133139131/6b016c24-1a79-48bb-b49a-e51f003bc33b)

**Comment by muno92** [comment]
Oh, it's typo.

Thank you!
