### ISSUE TITLE
Add the ability to dispay annotations for inspections lower than minimumSeverity

### ISSUE THREAD

**Issue by XmasApple** [muno92/resharper_inspectcode#415]

**Comment by muno92** [comment]
@XmasApple 
You can use minimumReportSeverity option.

For example)

- minimumSeverity
  - warning
- minimumReportSeverity
  - info

Output
- annotation
  - info or higher
- inspection job failed
  - when warning or error is exists

**Comment by XmasApple** [comment]
Thans
