### ISSUE TITLE
[URGENT] JetBrains.ReSharper.GlobalTools 2024.1.0 and higher is not supported

### ISSUE THREAD

**Issue by omer-za** [muno92/resharper_inspectcode#465]
The default output is no longer XML but JSON file from this version.

So basically since the default of this action is using latest version it's simply broken and doesn't really work anymore if version is not pinned to 2023.3.4 or lower

**Comment by omer-za** [comment]
Another possible fix is adding `-f=xml` to arguments but it will be deprecated soon according to CLI output
```
The XML format will soon be deprecated. Results in the XML format are still available in the current version using the -f="xml" parameter.
```

**Comment by n0099** [comment]
Can we just add `--format=xml` to a temporally workaround as upgrade to `2024.*` should fix https://github.com/dotnet/roslyn/issues/73508?

**Comment by muno92** [comment]
Exactly.

I specified format as a temporally workaround.

**Comment by muno92** [comment]
JetBrains.ReSharper.GlobalTools 2024.1.0 and higher is already supported.
